### ISSUE TITLE
YAML Untermenge von JSON?

### ISSUE THREAD

**Issue by rdmueller** [RobWin/javamagazin-article#1]
https://github.com/RobWin/javamagazin-article/blame/master/src/docs/asciidoc/index.adoc#L16

Laut Wikipedia kann YAML teilweise mehr als JSON und ist somit keine Untermenge:
https://en.wikipedia.org/wiki/YAML#JSON

Dennoch ist das Ziel von YAML ein JSON Subset zu sein... strange

**Comment by rdmueller** [comment]
Ich denke, ich habe das Problem gefunden: JSON ist ein Subset von YAML.
YAML-Parser können im allgemeinen JSON parsen...
YAML ist ein Superset von JSON

**Comment by RobWin** [comment]
Ok danke :+1:
